lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: "Neural Notes"
description: "You can find notes related to various machine learning and deep learning topics including knowledge about various tools and frameworks."
baseurl: ""
url: ""