title: "Neural Notes"
description: "You can find notes related to various machine learning and deep learning topics including knowledge about various tools and frameworks."
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Just the Docs theme settings
color_scheme: light
search_enabled: true
heading_anchors: true
nav_exclude: ['images']
aux_links:
  "GitHub":
    - "https://github.com/Krishan098/notes"

# Kramdown settings
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

highlighter: rouge
baseurl: "/notes"
url: "https://krishan098.github.io"